### PR TITLE
add project start_date to index

### LINKED ISSUE #152: Sorting projects by start date returns "No results"
Screenshot from 2020-04-16 23-10-54

Sorting projects by start dates does not work - returns no results

 - Deployment:  daisy-test.lcsb.uni.lu
 - Version  1.3.0

daisy log:
```
WARNING 2020-04-16 23:12:37,681 log 31208 139903498270528 Not Found: /favicon.ico
WARNING 2020-04-16 23:12:37,681 log 31208 139903498270528 Not Found: /favicon.ico
DEBUG 2020-04-16 23:12:44,787 utils 31208 139903498270528 search_objects query=None filter=defaultdict(<class 'list'>, {}) facets=('local_custodians', 'start_year', 'end_year', 'disease_terms', 'study_terms', 'phenotype_terms', 'gene_terms', 'has_cner', 'has_erp', 'has_legal_documents', 'funding_sources', 'company_personnel', 'contacts') model_object=<class 'core.models.project.Project'> order_by=None
WARNING 2020-04-16 23:12:45,371 log 31208 139903498270528 Not Found: /favicon.ico
WARNING 2020-04-16 23:12:45,371 log 31208 139903498270528 Not Found: /favicon.ico
DEBUG 2020-04-16 23:12:46,799 utils 31208 139903498270528 search_objects query=None filter=defaultdict(<class 'list'>, {}) facets=('local_custodians', 'start_year', 'end_year', 'disease_terms', 'study_terms', 'phenotype_terms', 'gene_terms', 'has_cner', 'has_erp', 'has_legal_documents', 'funding_sources', 'company_personnel', 'contacts') model_object=<class 'core.models.project.Project'> order_by=start_date
```

### PR DESCRIPTION
**Pull request by vildead**
Closes #152

### CODE REVIEW

**Review by pinarpink — COMMENTED** [review]
@vildead I am not sure if we should index based on date. I remember we had exact date indexing very early on in DAISY and it results in a veery long list in the StartDate facet box of Project search page

**Comment by vildead** [comment]
> @vildead I am not sure if we should index based on date. I remember we had exact date indexing very early on in DAISY and it results in a veery long list in the StartDate facet box of Project search page



@pinar - I see. That would be really long. But it seems the **Date** facet box is not there any more - just **Start/End Year**. 
We can change the ordering **Start date** to **Start year** - then there will be no need for the date in index. Let me know if you agree.

Screenshot from 2021-05-03 14-51-56

**Comment by pinarpink** [comment]
> > @vildead I am not sure if we should index based on date. I remember we had exact date indexing very early on in DAISY and it results in a veery long list in the StartDate facet box of Project search page
> 
> @pinar - I see. That would be really long. But it seems the **Date** facet box is not there any more - just **Start/End Year**.
> We can change the ordering **Start date** to **Start year** - then there will be no need for the date in index. Let me know if you agree.
> 
> Screenshot from 2021-05-03 14-51-56

If the newly prepared exact date index field will be used for sorting only then ignore my comments. I had assumed there would be a facet. Go ahead.

**Comment by vildead** [comment]
> > > @vildead I am not sure if we should index based on date. I remember we had exact date indexing very early on in DAISY and it results in a veery long list in the StartDate facet box of Project search page
> > 
> > 
> > @pinar - I see. That would be really long. But it seems the **Date** facet box is not there any more - just **Start/End Year**.
> > We can change the ordering **Start date** to **Start year** - then there will be no need for the date in index. Let me know if you agree.
> > Screenshot from 2021-05-03 14-51-56
> 
> If the newly prepared exact date index field will be used for sorting only then ignore my comments. I had assumed there would be a facet. Go ahead.

**Review by pinarpink — APPROVED** [review]

**Pull request merged**
