### PR TITLE
163 export as excel

### PR DESCRIPTION
**Pull request by jLebioda**
The superuser will see the following button:
Screenshot 2020-04-28 at 14 13 39

Once clicked, all the current filters and query will be applied, and excel spreadsheet will be created from the results.

This feature might require some tweaks (what information is required in the export, and how it should be formatted) and corrections (real data might cause some unforeseen problems) in the future.

### CODE REVIEW

**Comment by jLebioda** [comment]
WIP: I need to add permission restriction first

**Comment by vildead** [comment]
I am sorry - I have tested on test VM and I got nothing - blank page :disappointed: 
Here are daisy logs:
for datasets:
```
DEBUG 2020-04-28 22:47:01,046 utils 24403 140412039153472 search_objects query= filter=defaultdict(<class 'list'>, {'': ['']}) facets=('local_custodians', 'consent_status', 'data_types', 'deidentification_method', 'is_published') model_object=<class 'core.models.dataset.Dataset'> order_by=
```
for projects:
```
DEBUG 2020-04-28 22:49:05,199 utils 24403 140412039153472 search_objects query= filter=defaultdict(<class 'list'>, {'': ['']}) facets=('local_custodians', 'start_year', 'end_year', 'disease_terms', 'study_terms', 'phenotype_terms', 'gene_terms', 'has_cner', 'has_erp', 'has_legal_documents', 'funding_sources', 'company_personnel', 'contacts') model_object=<class 'core.models.project.Project'> order_by=
```

Priviledge-wise everything OK :) only superuser can see this button.

**Comment by jLebioda** [comment]
@vildead if it's completely blank page, then it means that the exporter hit the issues I talked about. I will review that.

Thanks for checking that!

**Comment by jLebioda** [comment]
I've protected the view by catching the exceptions, so that in case the exporter runs into problems, it should be caught and some debug information will be returned.

The issue described by @vildead was also resolved - turned out it was just something with the deployment procedure.

I will merge after receiving @vildead's and @pinarpink's approval

**Comment by vildead** [comment]
I works nicely at the moment. But current demo data are not very diverse. We should also test with new demo data once available.

**Comment by pinarpink** [comment]
I am working on the demo data branch. Should push today.

**Comment by vildead** [comment]
@jLebioda  I have submited a [merge request](https://github.com/elixir-luxembourg/daisy/pull/173) from my fork - I do not have permission to push directly to this MR :(

Please, could you review and (eventually) merge?

Once done, this can be merged too - tested on new demo data ;)

**Comment by jLebioda** [comment]
@vildead sure, done!

**Pull request merged**
