### PR TITLE
244 add publish parameter to importer

### PR DESCRIPTION
**Pull request by vildead**

### CODE REVIEW

**Comment by vildead** [comment]
- [ ] all records (datasets, partners, projects) should be first matched by elu_accession (if exists) ifelse by name ifelse by acronym
- [ ] can importer update published entity? (It wont change the elu_accesion string but can change everything else)
- [ ] check logics of entity matching:
- what if json contains elu_accession and entity does not?
- what if json does not contain elu_accesssion and entity does?
- what if json and entity have their elu_accession but they do not match? (only name or acronym matches)

**Comment by pinarpink** [comment]
@vildead looking at this now sorry for the delay.

**Review by pinarpink — CHANGES_REQUESTED** [review]
Hi Vilem I tried to verify this locally but the publishing behavior does not seem to work for me. I have put the steps I have done in the conversation tab.

**Comment by pinarpink** [comment]
@vildead  

For the review: I pulled this branch. Dropped and  recreated DAISY database then  ran load_initial_data  followed by the below commands
`python manage.py import_projects --publish-entities -f  ./data/demo/projects.json`
`python manage.py import_datasets --publish-entities -f  ./data/demo/datasets.json`

Then I went to check the demo data entities from the GUI none of them had an ID assigned or appeared published.

**Comment by vildead** [comment]
@pinarpink thank you for testing this. At the moment, the MR is work in progress. I took a look and you should get warning something like:
```
WARNING Publishing this type of entity (Dataset) is not implemented - item is not published. 
```
Which is actually true - the publishing feature is extended in MR [243](https://github.com/elixir-luxembourg/daisy/pull/243) which is not merged. Frankly I would like to wait till it is merged to develop rather then merging it now here.

If we need this feature soon, I can do "simple" publish and once the #243 is merged, I can update the importer to use the new function.

**Comment by pinarpink** [comment]
@vildead yes this is needed before 15 July for Smart4Health

**Comment by vildead** [comment]
matching and update logic:
  -  matched by external_id 
      -  db entity is published -> fail
      - db entity is not published -> continue and update all fields (and publish depending on --publish--entities flag)
  -  matched by name
      -  both have external_id
         -  db entity is published -> fail
         - db is not published -> continue and update all fields including external_id
      - only json has external_id -> update (and publish depending on --publish--entities flag)
      - only db has external_id
          - db entitye is published -> fail
          - db entitye is not published -> continue and update all fields

**Review by pinarpink — APPROVED** [review]
I will re-test this branch and #243 are both merged to develop

**Pull request merged**
