### PR TITLE
#103 add project info

### PR DESCRIPTION
**Pull request by jLebioda**
Inside contracts list, project name will be appended: _Partner's name (on Project's name)_, e.g.:
Max Rubner-Institut (on Project-name)

### CODE REVIEW

**Comment by vildead** [comment]
@jLebioda, could be please the project information added also to dropdown list in Data declaration editor page? That's where the user is usually struggling with long list of contracts.

@pinarpink Are there any cases/projects with more than one contract with the same collaborator? This rare case would again result in ambiguity. Contract ID could be also added to be sure...

**Comment by jLebioda** [comment]
@vildead sure, will do!

**Comment by jLebioda** [comment]
@vildead Could you please take a look one more time? The project information should already appear under the form.

Regarding contract-ID, could you give an example? Would it be 

    #123 Max Rubner-Institut (on Lorem Ipsum)

**Comment by pinarpink** [comment]
Addition of Project info to string rep of Contract is  verified on 279f74606663a094a983d6547fc0fec279268d54.  in dev env

 @jLebioda   thank you so much. I am no expert on usability and UX,  before we merge can we replace "on" with a symbol "-"; or perhaps put the project in parentheses. Otherwise it reads like one long name.

@jLebioda @vildead  The Contract ID will be a number/label given to the contract by the relevant ServiceNOW module. Indeed there can be multiple contracts with same partner, and ID is helpful there. But, I suggest that for now we close this issue, it is best if the legal team define requirements re: contract IDs/Labels

**Comment by jLebioda** [comment]
Ok, sure :)

**Comment by jLebioda** [comment]
@pinarpink I've corrected it, now it reads like the following:
image

**Pull request merged**
